name: Build WebRTC AAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git python3 python3-pip openjdk-17-jdk unzip curl build-essential

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git

    - name: Set PATH for depot_tools
      run: |
        echo "${{ github.workspace }}/depot_tools" >> $GITHUB_PATH

    - name: Fetch WebRTC Android source
      run: |
        mkdir webrtc-checkout
        cd webrtc-checkout
        export PATH="${{ github.workspace }}/depot_tools:$PATH"
        fetch --nohooks webrtc_android
        cd src
        gclient sync

    - name: Build AARs (arm64, x86_64, armeabi-v7a)
      run: |
        cd webrtc-checkout/src
        export PATH="${{ github.workspace }}/depot_tools:$PATH"

        # ARM64
        gn gen out/arm64 --args='target_os="android" target_cpu="arm64" is_debug=false rtc_include_tests=false'
        ninja -C out/arm64 sdk

        # x86_64
        gn gen out/x86_64 --args='target_os="android" target_cpu="x86_64" is_debug=false rtc_include_tests=false'
        ninja -C out/x86_64 sdk

        # armeabi-v7a
        gn gen out/armeabi-v7a --args='target_os="android" target_cpu="arm" is_debug=false rtc_include_tests=false'
        ninja -C out/armeabi-v7a sdk

    - name: Upload AAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webrtc-aar
        path: |
          webrtc-checkout/src/out/arm64/lib.java/sdk/android/libwebrtc.aar
          webrtc-checkout/src/out/x86_64/lib.java/sdk/android/libwebrtc.aar
          webrtc-checkout/src/out/armeabi-v7a/lib.java/sdk/android/libwebrtc.aar
